"""Host library for hidpin devices (see docs/PROTOCOL.md)."""

from hidpin.device import (
    Device,
    DeviceEntry,
    HidpinError,
    PinConfigConflict,
    PinConfigRejected,
    ProtocolVersionError,
    PullDownUnreliableWarning,
    find_devices,
)
from hidpin.protocol import (
    PROTOCOL_VERSION,
    Board,
    Chip,
    DeviceInfo,
    EdgeEvent,
    PinConfig,
    PinConfigReport,
    PinMode,
    PinSetting,
    Quirk,
    Reason,
    Result,
    StatusFlags,
    StatusReport,
)

__all__ = [
    "PROTOCOL_VERSION",
    "Board",
    "Chip",
    "Device",
    "DeviceEntry",
    "DeviceInfo",
    "EdgeEvent",
    "HidpinError",
    "PinConfig",
    "PinConfigConflict",
    "PinConfigRejected",
    "PinConfigReport",
    "PinMode",
    "PinSetting",
    "ProtocolVersionError",
    "PullDownUnreliableWarning",
    "Quirk",
    "Reason",
    "Result",
    "StatusFlags",
    "StatusReport",
    "find_devices",
]
